# Generated by Django 3.0.8 on 2020-07-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200730_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='count_tracks',
            field=models.PositiveIntegerField(default=0, verbose_name='Колличество композиций'),
        ),
    ]
