# Generated by Django 3.0.8 on 2020-07-30 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200730_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='date_created',
            field=models.DateField(default=0, verbose_name=datetime.date),
            preserve_default=False,
        ),
    ]
